force-app/main/default/objects/Vehicle_Inventory_Item__c/Vehicle_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>Items that are stored in the Warehouse and Reassignable to vehicles</description>
    <label>Inventory Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Collection__c.field-meta.xml
<CustomField>
    <fullName>Collection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Collection associated to the item</description>
    <label>Collection</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <description>Manufacturer of Inventory Item</description>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Model number of the Inventory Item</description>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <description>Order number of the purchased Inventory Item</description>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <description>Purchase date of the Inventory Item</description>
    <label>Purchase Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Purchased_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Quantity__c</fullName>
    <description>Number of items purchased</description>
    <label>Purchased Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <description>Purchased Inventory Item from</description>
    <label>Reseller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of ordered assets</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Researching</fullName>
                <default>true</default>
                <label>Researching</label>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Stocked</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
                <label>Stocked</label>
            </value>
            <value>
                <fullName>Depleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total Price of the ordered quantity of Inventory Items</description>
    <label>Total Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of inventory</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_Item_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price of each Inventory Item</description>
    <label>Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/recordTypes/Tool.recordType-meta.xml
<RecordType>
    <fullName>Tool</fullName>
    <active>true</active>
    <description>Tool used for maintenance</description>
    <label>Tool</label>
</RecordType>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Collection of Tools, Parts, and Consumables</description>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Warehouse_Item_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Body</fullName>
    </customValue>
    <customValue>
        <fullName>Detailing</fullName>
        <default>true</default>
        <label>Detailing</label>
    </customValue>
    <customValue>
        <fullName>Electrical System</fullName>
    </customValue>
    <customValue>
        <fullName>Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Mechanical System</fullName>
    </customValue>
    <description>Type of Inventory that support the Motor Head App.</description>
    <masterLabel>Warehouse Item Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/VehicleInventoryItemTriggerHandlerTest.cls
@isTest
public class VehicleInventoryItemTriggerHandlerTest {
    // Constants
    // Unit Price
    static FINAL decimal unitPrice = 4.00;
    static FINAL decimal totalPrice = 60.00;
    
    @TestSetup
    static void testWarehouse(){
        Warehouse__c testWarehouse = new Warehouse__c(Name='Detailing Towels');
        insert testWarehouse;
    }
    @isTest
    public static void testEmptyUnitCost(){
        List <Warehouse__c> wh = [SELECT Id, Name FROM Warehouse__c];
        
        Test.startTest();
        Id toolRT = Schema.SObjectType.Vehicle_Inventory_Item__c.getRecordTypeInfosByName().get('Tool').getRecordTypeId();
        Vehicle_Inventory_Item__c testTowel = new Vehicle_Inventory_Item__c(Name='Red Buffing Towels',Collection__c=wh[0].Id,RecordTypeId=toolRT,Manufacturer__c='AMMO NYC',Model__c='12RMF',Order_Number__c='ANYC1001',Purchase_Date__c=system.today(),Reseller__c='AMMO NYC',Status__c='Ordered',Type__c='Detailing',Purchased_Quantity__c=12,Total_Price__c=48);
        insert testTowel;
        System.assertEquals(unitPrice, [SELECT Id, Unit_Price__c FROM Vehicle_Inventory_Item__c].Unit_Price__c, 'Unit Price should be 4');
        Test.stopTest();
    }
    @isTest
    public static void testEmptyTotalCost(){
        List <Warehouse__c> tcwh = [SELECT Id, Name FROM Warehouse__c];
        
        Test.startTest();
        Id toolRT = Schema.SObjectType.Vehicle_Inventory_Item__c.getRecordTypeInfosByName().get('Tool').getRecordTypeId();
        Vehicle_Inventory_Item__c testTowelUnit = new Vehicle_Inventory_Item__c(Name='Red Buffing Towels',Collection__c=tcwh[0].Id,RecordTypeId=toolRT,Manufacturer__c='AMMO NYC',Model__c='12RMF',Order_Number__c='ANYC1001',Purchase_Date__c=system.today(),Reseller__c='AMMO NYC',Status__c='Ordered',Type__c='Detailing',Purchased_Quantity__c=12,Unit_Price__c=5);
        insert testTowelUnit;
        System.assertEquals(totalPrice, [SELECT Id, Total_Price__c FROM Vehicle_Inventory_Item__c].Total_Price__c, 'Total Price should be '+totalPrice);
        Test.stopTest();
    }

}