force-app/main/default/objects/Vehicle_Inventory_Item__c/Vehicle_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>Items that are stored in the Warehouse and Reassignable to vehicles</description>
    <label>Inventory Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Purchased_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Quantity__c</fullName>
    <description>Number of items purchased</description>
    <label>Purchased Quantity</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total Price of the ordered quantity of Inventory Items</description>
    <label>Total Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price of each Inventory Item</description>
    <label>Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/VehicleInventoryItemTriggerHandler.cls
public class VehicleInventoryItemTriggerHandler {
    public void beforeDML(List <Vehicle_Inventory_Item__c> updateInventory){
        for(Vehicle_Inventory_Item__c vii : updateInventory){
            if(vii.Total_Price__c == null && vii.Purchased_Quantity__c > 0){
                vii.Total_Price__c = vii.Purchased_Quantity__c * vii.Unit_Price__c;
            }
            else if(vii.Unit_Price__c == null && vii.Purchased_Quantity__c > 0){
                vii.Unit_Price__c = vii.Total_Price__c / vii.Purchased_Quantity__c;
            }
        }
    }

}