force-app/main/default/objects/Job_Resource__c/Job_Resource__c.object-meta.xml
<CustomObject>
    <description>Tools, Parts, and Consumables needed to complete a maintenance job.</description>
    <label>Job Resource</label>
    <nameField>
        <displayFormat>JM-{0000}</displayFormat>
        <label>Job Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Resource__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to inventory item needed for a Job.</description>
    <label>Inventory Item</label>
    <referenceTo>Vehicle_Inventory_Item__c</referenceTo>
    <relationshipLabel>Job Resources</relationshipLabel>
    <relationshipName>Job_Resources</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Resource__c/fields/Required_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Required_Quantity__c</fullName>
    <description>Quantity to required to complete Job</description>
    <label>Required Quantity</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Resource__c/fields/Vehicle_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Maintenance__c</fullName>
    <description>Master lookup to Maintenance Job</description>
    <label>Vehicle Maintenance</label>
    <referenceTo>Vehicle_Maintenance__c</referenceTo>
    <relationshipLabel>Job Resources</relationshipLabel>
    <relationshipName>Job_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Track Vehicle information</description>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <description>Manufacturer of the Vehicle</description>
    <label>Make</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Model of the Vehicle</description>
    <label>Model</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>Vehicle Year</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/Vehicle_Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>Items that are stored in the Warehouse and Reassignable to vehicles</description>
    <label>Inventory Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Inventory Item</description>
    <label>Description</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <description>Manufacturer of Inventory Item</description>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <description>Model number of the Inventory Item</description>
    <label>Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of ordered assets</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Researching</fullName>
                <default>true</default>
                <label>Researching</label>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Stocked</fullName>
            </value>
            <value>
                <fullName>Installed</fullName>
                <label>Stocked</label>
            </value>
            <value>
                <fullName>Depleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of inventory</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Warehouse_Item_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price of each Inventory Item</description>
    <label>Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vehicle the Item is associated to</description>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Inventory_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle_Inventory_Item__c/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part that is used for a job and reassociated to the vehicle permanently</description>
    <label>Part</label>
</RecordType>

force-app/main/default/objects/Vehicle_Maintenance__c/Vehicle_Maintenance__c.object-meta.xml
<CustomObject>
    <description>Track Maintenance on Vehicles</description>
    <label>Vehicle Maintenance</label>
    <nameField>
        <label>Vehicle Maintenance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Maintenances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Maintenance__c/fields/Issue__c.field-meta.xml
<CustomField>
    <fullName>Issue__c</fullName>
    <description>Problem or reason for Maintenance</description>
    <label>Issue</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle_Maintenance__c/fields/Parts__c.field-meta.xml
<CustomField>
    <fullName>Parts__c</fullName>
    <description>Parts cost</description>
    <label>Parts</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle_Maintenance__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <description>Master vehicle record</description>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Vehicle Maintenances</relationshipLabel>
    <relationshipName>Vehicle_Maintenances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle_Maintenance__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <description>Type of Work for Vehicle Maintenance</description>
    <label>Work Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Work_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Maintenance__c/recordTypes/DIY.recordType-meta.xml
<RecordType>
    <fullName>DIY</fullName>
    <active>true</active>
    <description>DIY Maintenance</description>
    <label>DIY</label>
</RecordType>

force-app/main/default/globalValueSets/Vehicle_Work_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Body</fullName>
    </customValue>
    <customValue>
        <fullName>Consumable</fullName>
    </customValue>
    <customValue>
        <fullName>Detailing</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Mechanical</fullName>
    </customValue>
    <description>Universal picklist for Vehicle Work - includes tools, parts, and maintenance</description>
    <masterLabel>Vehicle Work Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Warehouse_Item_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Body</fullName>
    </customValue>
    <customValue>
        <fullName>Detailing</fullName>
        <default>true</default>
        <label>Detailing</label>
    </customValue>
    <customValue>
        <fullName>Electrical System</fullName>
    </customValue>
    <customValue>
        <fullName>Interior</fullName>
    </customValue>
    <customValue>
        <fullName>Mechanical System</fullName>
    </customValue>
    <description>Type of Inventory that support the Motor Head App.</description>
    <masterLabel>Warehouse Item Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/motorHeadFlowsTest.cls
//**********************************************************************************//
//	This test class tests the following flows part of the Motorhead App				//
//	jobResourceTriggeringFlow - runs when Job_Resource__c record is created/updated	//
//	vehicleMaintenanceCalculateFlow - calculates Cost for vehicleMaintenance		//
//**********************************************************************************//	
@isTest
public class motorHeadFlowsTest {
    
    // Constants
    // Final Value of the Vehicle Maintenance
    static final decimal TOTAL_COST = 4203.20;
        
    @TestSetup
    static void testMotorHeadData(){
        //Create Vehicle__c
        Vehicle__c testSUV = new Vehicle__c(Name='G-Wagen',Make__c='Mercedes-Benz',Model__c='G550',Year__c='2021');
        insert testSUV;
        
        //Create Vehicle_Maintenance__c record
        Vehicle_Maintenance__c testJob = new Vehicle_Maintenance__c(Name='New Shoes', RecordTypeId=Schema.SObjectType.Vehicle_Maintenance__c.getRecordTypeInfosByName().get('DIY').getRecordTypeId(), Vehicle__c=testSUV.Id,Work_Type__c='Mechanical',Issue__c='Daddy needs new shoes');
        insert testJob;
        
        // Create a Tire record
        Vehicle_Inventory_Item__c testTire = new Vehicle_Inventory_Item__c(Name='275-55 Tires',Vehicle__c=testSUV.Id, RecordTypeId=Schema.SObjectType.Vehicle_Inventory_Item__c.getRecordTypeInfosByName().get('Part').getRecordTypeId(),Description__c='275/55R19 SUV Tires',Manufacturer__c='Pirelli', Model__c='Scorpion AS Plus',Status__c='Stocked',Unit_Price__c=300.80,Type__c='Mechanical System');
        insert testTire;
        
        // Create a Wheel record
        Vehicle_Inventory_Item__c testWheel = new Vehicle_Inventory_Item__c(Name='19" AMG Wheels',Vehicle__c=testSUV.Id, RecordTypeId=Schema.SObjectType.Vehicle_Inventory_Item__c.getRecordTypeInfosByName().get('Part').getRecordTypeId(),Description__c='19" AMG Wheels',Manufacturer__c='AMG', Model__c='Twin 5 Spoke',Status__c='Stocked',Unit_Price__c=750,Type__c='Mechanical System');
        insert testWheel;
        
    }
    // Test adding Resources to a Job
    @isTest
    public static void insertJobResourceRecords(){
        
        List<Vehicle_Maintenance__c> maintenances = [SELECT Id, Name, Vehicle__c FROM Vehicle_Maintenance__c];
        //Vehicle_Maintenance__c maintenance = maintenances[0];
        List<Vehicle_Inventory_Item__c> toys = [SELECT Id, Vehicle__c,Unit_Price__c FROM Vehicle_Inventory_Item__c];
        // Test Creating Job Resource
        Test.startTest();
        
        List<Job_Resource__c> resources = new List<Job_Resource__c>();
        for(Vehicle_Inventory_Item__c toy : toys){
            resources.add(new Job_Resource__c(Vehicle_Maintenance__c=maintenances[0].Id, Inventory_Item__c=toy.Id, Required_Quantity__c=4));
        }
        insert resources;
        
        
        // Validate Vehicle_Maintenance__c cost update
        System.assertEquals(TOTAL_COST, [SELECT Id, Parts__c FROM Vehicle_Maintenance__c].Parts__c, 'Part cost should equal the TOTAL_COST constant defined in the test class');
        
        Test.stopTest();     
    }
    
    
}